<?php
/**
 * Implements hook_form_FORM_ID_alter
 */
function commerce_checkout_after_new_password_form_user_profile_form_alter(&$form, &$form_state, $form_id){
  $form['#submit'][] = 'commerce_checkout_after_new_password_user_profile_submit';
}

/**
 * Implements hook_module_implements_alter().
 * Make sure that our hook_form_FORM_ID_alter is called last so our submit handler is the final one.
 */
function commerce_checkout_after_new_password_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'hook_form_user_profile_alter') {
    $module = 'commerce_checkout_after_new_password';
    $this_implementation = array($module => $implementations[$module]);
    unset($implementations[$module]);
    $implementations = $this_implementation + $implementations;
  }
}

/**
 * Submit handler for user profile page, added last, redirects to checkout if order is set.
 */
function commerce_checkout_after_new_password_user_profile_submit($form, &$form_state){
  global $user;
  $order = commerce_cart_order_load($user->uid);
  if (!empty($order) && isset($order->order_number)) {
    unset($form_state['redirect']);
    $_GET['destination'] = 'checkout/' . (int) $order->order_number;
  }
}